#!/bin/sh 

name_ver(){
	cat /etc/os-release | grep -i PRETTY_NAME | awk -F "=" '{print $2}' | awk -F '"' '{print $2}'
}


ver(){
    cat /etc/os-release | grep -i VERSION_ID | awk -F "=" '{print $2}' | awk -F '"' '{print $2}'
}

support(){
       cat /etc/os-release | grep -i SUPPORT_URL | awk -F "=" '{print $2}' | awk -F '"' '{print $2}'
}

name(){
    cat /etc/os-release | grep -i NAME | awk -F "=" '{print $2}' | awk -F '"' '{print $2}' | sed -n 'n;p'
}


kernel_ver(){
          cat /proc/version | awk '{print $3}'
}


case $1 in
     -nv)
	name_ver
	;;


      -v)
	ver
	;;

      -s)
        support
	;;

      -n)
        name
	;;

      -k)
        kernel_ver
	;;

      -h)
        echo "
	-nv: distro name & version

        -v: distro version

	-s: distro support page

        -n: distro name

	-k: get kernel version

	-h: list program options"
	;;

       *)
        echo "
	-nv: distro name & version

        -v: distro version

	-s: distro support page

        -n: distro name

	-k: get kernel version

	-h: list program options"
	;;
esac
